# Generated by Django 4.0.4 on 2022-05-13 23:37

import controle.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Poupança', 'Poupança'), ('Crédito', 'Crédito'), ('Corrente', 'Corrente')], max_length=200)),
                ('limite', models.FloatField(default=0)),
                ('limite_usado', models.FloatField(default=0)),
                ('limite_restante', models.FloatField(default=0)),
                ('valor', models.FloatField(default=0)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Compra', 'Compra'), ('Compra Parcelada', 'Compra Parcelada'), ('Pagamento Fatura', 'Pagamento Fatura'), ('Transferência', 'Transferência'), ('Poupança', 'Poupança'), ('Outros', 'Outros')], max_length=200)),
                ('parcela', models.IntegerField()),
                ('valor', models.FloatField()),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[(controle.models.Entrada, 'Entrada'), (controle.models.Saida, 'Saida')], max_length=200)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Salário', 'Salário'), ('Transferência', 'Transferência'), ('Outros', 'Outros')], max_length=200)),
                ('valor', models.FloatField()),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.conta')),
            ],
        ),
    ]
