# Generated by Django 4.0.4 on 2022-05-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='foto',
            field=models.ImageField(default='', upload_to='banco'),
            preserve_default=False,
        ),
    ]
