# Generated by Django 4.0.4 on 2022-05-14 12:34

import controle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_banco_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrato',
            name='tipo',
            field=models.CharField(choices=[('Entrada', controle.models.Entrada), ('Saida', controle.models.Saida)], max_length=200),
        ),
    ]
