# Generated by Django 4.0.4 on 2022-05-14 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_alter_extrato_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrato',
            name='entrada',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='controle.entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrato',
            name='saida',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='controle.saida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extrato',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'Saida')], max_length=200),
        ),
    ]
