# Generated by Django 4.0.4 on 2022-05-14 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_extrato_entrada_extrato_saida_alter_extrato_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrato',
            name='entrada',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='controle.entrada'),
        ),
        migrations.AlterField(
            model_name='extrato',
            name='saida',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='controle.saida'),
        ),
    ]
