# Generated by Django 4.0.4 on 2022-05-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_alter_extrato_entrada_alter_extrato_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrato',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controle.entrada'),
        ),
    ]
