# Generated by Django 4.0.4 on 2022-05-14 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0006_alter_extrato_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrato',
            name='saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controle.saida'),
        ),
    ]
