# Generated by Django 4.0.4 on 2022-05-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0007_alter_extrato_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='tipo',
            field=models.CharField(choices=[('Salário', 'Salário'), ('Transferência', 'Transferência'), ('Pagamento Fatura', 'Pagamento Fatura'), ('Outros', 'Outros')], max_length=200),
        ),
    ]
