# Generated by Django 4.0.4 on 2022-05-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0008_alter_entrada_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='foto',
            field=models.ImageField(blank=True, upload_to='banco'),
        ),
    ]
